spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weatherinfo?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myuser
    password: myuser

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

open-weather:
  api:
   key: "77d09da501b4123619e80ae0cee2f8ec"